name : Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install node js
        uses: actions/setup-node@v2
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm test